# Core configuration (read from the live instance's /api/config).
homeassistant:
  name: Home
  latitude: -41.27266816174775
  longitude: 174.78256970644
  elevation: 0
  unit_system: metric
  currency: NZD
  country: NZ
  language: en-GB
  time_zone: Pacific/Auckland
  packages: !include_dir_named packages/

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# Automations created in the ui
automation ui: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# enable api
api:

# database to store history
recorder:
  # note, this is hard coded in the secret.yaml file, i couldnt figure out how to reference a env var as a substring
  db_url: !secret postgres_connection_string
  auto_purge: false

# themes
frontend:
  themes: !include_dir_merge_named themes

# Lovelace dashboards
lovelace:
  mode: storage
  dashboards:
    lovelace-monitoring:
      mode: yaml
      title: Monitoring
      filename: dashboards/monitoring.yaml
      show_in_sidebar: true

# locations (Zones)
zone:
  - name: Home
    latitude: -41.27271120008771
    longitude: 174.78234880222823
    radius: 50
    icon: mdi:home
  - name: Bens Work
    latitude: -41.2924976
    longitude: 174.7782922
    radius: 50
    icon: mdi:map-marker
