# Leak

automation:
  - id: leak_alert
    alias: Leak Alert
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_detector_1_water_leak
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.water_leak_detector_2_water_leak
      from: 'off'
      to: 'on'
    action:
    - service: switch.turn_off
      target:
        entity_id: switch.hydro_pump
    - service: notify.notify
      data:
        message: "Water Leak Detected!"
        title: "Water Leak"
