# Wake Up Lights

input_boolean:
  wake_up_lights_mondays:
    name: "Monday"
    icon: mdi:calendar-week
  wake_up_lights_tuesdays:
    name: "Tuesday"
    icon: mdi:calendar-week
  wake_up_lights_wednesdays:
    name: "Wednesday"
    icon: mdi:calendar-week
  wake_up_lights_thursdays:
    name: "Thursday"
    icon: mdi:calendar-week
  wake_up_lights_fridays:
    name: "Friday"
    icon: mdi:calendar-week
  wake_up_lights_saturdays:
    name: "Saturday"
    icon: mdi:calendar-week
  wake_up_lights_sundays:
    name: "Sunday"
    icon: mdi:calendar-week

input_datetime:
  wake_up_lights_set_time:
    name: "Start Time"
    has_date: false
    has_time: true
    icon: mdi:alarm

input_number:
  wake_up_lights_fade_minutes:
    name: 'Pre Alarm fade-in time'
    min: 1
    max: 90
    step: 1
    initial: 30
    mode: box
    icon: mdi:timer-outline
    unit_of_measurement: min
  wake_up_lights_minutes:
    name: 'Post Alarm Light time'
    min: 1
    max: 90
    step: 1
    initial: 30
    mode: box
    icon: mdi:timer-outline
    unit_of_measurement: min

# sensor: Wake Up Lights ??? I forget what I was doing here, perhaps should be an automation
template:
  - sensor:
      - name: "Lights Timer"
        unique_id: wake_up_lights_time_ends
        icon: mdi:alarm-off
        state: >
          {{ (((state_attr('input_datetime.wake_up_lights_set_time' , 'timestamp'))
          + ((states('input_number.wake_up_lights_fade_minutes') | int(0) * 60)
          + states('input_number.wake_up_lights_minutes') | int(0) * 60))|timestamp_custom('%H:%M', false)) }}

automation:
  - id: id_wake_up_lights
    alias: Wake-Up Lights
    description: Turn lights on in specific time, on preset days
    trigger:
    - platform: time
      at: input_datetime.wake_up_lights_set_time
    condition:
    - condition: or
      conditions:
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 1 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_mondays
          state: 'on'
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 2 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_tuesdays
          state: 'on'
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 3 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_wednesdays
          state: 'on'
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 4 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_thursdays
          state: 'on'
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 5 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_fridays
          state: 'on'
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 6 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_saturdays
          state: 'on'
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ now().isoweekday() == 7 }}'
        - condition: state
          entity_id: input_boolean.wake_up_lights_sundays
          state: 'on'
    variables:
      entities: light.nightlight
      transition: '{{ states(''input_number.wake_up_lights_fade_minutes'') | int(0) * 60
        }}'
    action:
    - service: light.turn_on
      target:
        entity_id: '{{ entities }}'
      data:
        brightness_pct: 100
        color_temp_kelvin: 2500
        transition: '{{ transition }}'
    - delay:
        minutes: '{{ [(states(''input_number.wake_up_lights_fade_minutes'') | int(0)) +
          (states(''input_number.wake_up_lights_minutes'') | int(0)), 1] | max }}'
    - service: light.turn_off
      target:
        entity_id: '{{ entities }}'
